name: build every commit
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install podman
        run: |
          set -x
          sudo apt-get remove -y podman docker-ce docker docker-engine docker.io containerd runc ||:
          echo  "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_$( lsb_release -rs )/ /" | sudo tee /etc/apt/sources.list.d/podman.list /dev/null
          sudo apt-get update --allow-unauthenticated --allow-insecure-repositories
          sudo apt-get install -y podman
          sudo apt autoremove -y
      - run: podman build . -t poncho-builder
      - run: podman run --rm -it -v "$(pwd)":'/poncho' poncho-builder
      - run: mv target/scala-*/poncho-out poncho
      - uses: actions/upload-artifact@v3
        with:
          path: poncho
          name: poncho
